version: 2
updates:
    - package-ecosystem: gomod
      directory: /
      schedule:
        interval: daily
        time: "04:00" # UTC
      labels:
        - "deps"
      commit-message:
        prefix: "chore(go deps)"
    - package-ecosystem: npm
      directory: ui
      schedule:
        interval: daily
        time: "04:00" # UTC
      labels:
        - "deps"
        - "ui"
      commit-message:
        prefix: "chore(ui deps)"
