version: "3"

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: foo
      MINIO_SECRET_KEY: password
    ports:
      - 9999:9000
    volumes:
      - minio:/data
    command: server /data

  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - 9092:9092
    volumes:
      - prom:/data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data
      - --web.enable-lifecycle
      - --storage.tsdb.min-block-duration=2h
      - --storage.tsdb.max-block-duration=2h
      - --web.listen-address=0.0.0.0:9092

  querier:
    image: thanosio/thanos:v0.18.0
    ports:
      - 9998:9090
    command:
      - query
      - --http-address=:9090
      - --store=receiver_0:10907
      - --store=receiver_1:10907
      - --store=receiver_2:10907
    depends_on:
      - receiver_0
      - receiver_1
      - receiver_2

  receiver_0:
    image: thanosio/thanos:master-2021-01-28-8967a8cf
    restart: always
    volumes:
      - receive:/data
      - ./bucket.yml:/bucket.yml
      - ./hashring.json:/hashring.json
    ports:
      - 10000:10909
    command:
      - receive
      # - --log.level=debug
      - --log.format=logfmt
      - --tsdb.path=/data
      - --grpc-address=0.0.0.0:10907
      - --http-address=0.0.0.0:10909
      - --receive.replication-factor=3
      - --label=replication="0"
      - --label=cluster="test"
      - --receive.local-endpoint=receiver_0:10907
      - --receive.hashrings-file=/hashring.json
      - --remote-write.address=0.0.0.0:10908
      - --objstore.config-file=/bucket.yml
    depends_on:
      - minio
      - prometheus

  receiver_1:
    image: thanosio/thanos:master-2021-01-28-8967a8cf
    restart: always
    volumes:
      - receive:/data
      - ./bucket.yml:/bucket.yml
      - ./hashring.json:/hashring.json
    ports:
      - 10001:10909
    command:
      - receive
      - --tsdb.path=/data
      - --grpc-address=0.0.0.0:10907
      - --http-address=0.0.0.0:10909
      - --receive.replication-factor=3
      - --label=replication="1"
      - --label=cluster="test"
      - --receive.local-endpoint=receiver_1:10907
      - --receive.hashrings-file=/hashring.json
      - --remote-write.address=0.0.0.0:10908
      - --objstore.config-file=/bucket.yml
    depends_on:
      - minio
      - prometheus

  receiver_2:
    image: thanosio/thanos:master-2021-01-28-8967a8cf
    restart: always
    volumes:
      - receive:/data
      - ./bucket.yml:/bucket.yml
      - ./hashring.json:/hashring.json
    ports:
      - 10002:10909
    command:
      - receive
      - --tsdb.path=/data
      - --grpc-address=0.0.0.0:10907
      - --http-address=0.0.0.0:10909
      - --receive.replication-factor=3
      - --label=replication="2"
      - --label=cluster="test"
      - --receive.local-endpoint=receiver_2:10907
      - --receive.hashrings-file=/hashring.json
      - --remote-write.address=0.0.0.0:10908
      - --objstore.config-file=/bucket.yml
    depends_on:
      - minio
      - prometheus

volumes:
  minio: { }
  prom: { }
  receive: { }