openapi: 3.0.1
info:
  title: Manta HTTP API
  version: 1.0.0

servers:
  - url: /api/v1

tags:
  - name: Setup
  - name: Organization
  - name: User
  - name: Dashboard

paths:
  /setup:
    post:
      operationId: Setup
      tags:
        - Setup
      summary: Setup manta
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      requestBody:
        description: User and Organization to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OnBoardingRequest"
      responses:
        201:
          description: Create success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  parameters:
    TraceSpan:
      in: header
      name: Zap-Trace-Span
      schema:
        type: string
      description: OpenTracing span context
      example:
        trace_id: "1"
        span_id: "1"
        baggage:
          key: value
      required: false

  schemas:
    OnBoardingRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        organization:
          type: string

    Error:
      properties:
        code:
          description: Code is the machine-readable error code.
          readOnly: true
          type: string
          enum:
            - internal error
            - not found
            - conflict
            - invalid
            - unprocessable entity
            - empty value
            - unavailable
            - forbidden
            - too many requests
            - unauthorized
            - method not allowed
        message:
          readOnly: true
          description: Message is a human-readable message.
          type: string
      required: [ code, message ]