extensions:
  pprof:
    endpoint: 0.0.0.0:1234
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:

exporters:
  logging:
  prometheus:
    endpoint: 0.0.0.0:8889
  prometheusremotewrite:
    endpoint: http://localhost:10080/receive
    headers:
      X-Scope-OrgID: 5ca1ab1eba5eba11

service:
  pipelines:
    metrics:
      receivers:
        - hostmetrics
      exporters:
        - prometheus
        - logging
        - prometheusremotewrite

  extensions:
    - zpages
    - pprof
