extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:

exporters:
  logging:
  prometheus:
    endpoint: 0.0.0.0:8889
  prometheusremotewrite:
    endpoint: http://localhost:10080/receive

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus, logging, prometheusremotewrite]

  extensions: [zpages]
