name: Build

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs:
      - cancel-previous
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn
          cache-dependency-path: 'ui/yarn.lock'
      - run: make
