name: Test

on:
  workflow_dispatch: {}
  pull_request: {}

env:
  CI: true

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

  go_test:
    name: Go test
    runs-on: ubuntu-20.04
    needs:
      - cancel-previous
    steps:
      - uses: actions/checkout@2.4.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...

  ui_test:
    name: UI test
    runs-on: ubuntu-20.04
    needs:
      - cancel-previous
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
        working-directory: ./ui
      - run: yarn build
        working-directory: ./ui