name: Build

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true

  go_test:
    name: Go test
    runs-on: ubuntu-20.04
    needs:
      - cancel-previous
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    needs:
      - cancel-previous
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
          cache-dependency-path: 'ui/yarn.lock'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: prettier
        run: cd ui && yarn

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs:
      - cancel-previous
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
          cache-dependency-path: 'ui/yarn.lock'
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: mantad
          path: bin/mantad
          if-no-files-found: error

  cypress:
    name: Cypress
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: mantad
          path: ./mantad

      - name: Run
        run: chmod +x ./mantad && nohup ./mantad &

      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          project: ./ui/cypress
          working-directory: ./ui
