openapi: 3.0.1
info:
  title: Manta HTTP API
  version: 1.0.0

servers:
  - url: /api/v1

tags:
  - name: Organizations
  - name: Otcls
    description: OpenTelemetry Collector

paths:
  /setup:
    post:
      operationId: Setup
      tags:
        - Setup
      summary: Setup the service
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      requestBody:
        description: User and Organization to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OnBoardingRequest"
      responses:
        201:
          description: Initial success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /orgs:
    get:
      operationId: GetOrgs
      tags:
        - Organizations
      summary: List all organizations
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      responses:
        200:
          description: A list of organizations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organizations"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: CreateOrg
      tags:
        - Organizations
      summary: Create an Organization
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      requestBody:
        description: Organization to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organization"
      responses:
        201:
          description: Organization created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
  /orgs/{orgID}:
    get:
      operationId: GetOrgByID
      tags:
        - Organizations
      summary: Retrieve an organization
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: orgID
          schema:
            type: string
          required: true
          description: The ID of the organization to get
      responses:
        200:
          description: Organization details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /otcls:
    get:
      operationId: GetOtcls
      tags:
        - Otcls
      summary: List all OpenTelemetry Collector
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      responses:
        200:
          description: A list of Otcl
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Otcl"
        default:
          $ref: "#/components/responses/UnexpectedError"

    post:
      operationId: CreateOtcl
      tags:
        - Otcls
      summary: Create an Otcl
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      requestBody:
        description: Otcl to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OtclRequest"
      responses:
        201:
          description: Otcl created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Otcl"
        default:
          $ref: "#/components/responses/UnexpectedError"
  /otcls/{otclID}:
    get:
      operationId: GetOtcl
      tags:
        - Otcls
      summary: Get Otcl by ID
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: otclID
          schema:
            type: string
          required: true
          description: The ID of the Otcl to get
      responses:
        200:
          description: Otcl details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Otcl"
        default:
          $ref: "#/components/responses/UnexpectedError"

  /checks:
    get:
      operationId: ListChecks
      tags:
        - Checks
      summary: List al Checks
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: query
          name: orgID
          description: List checks with this orgID
          required: false

      responses:
        200:
          description: Check List
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Checks"
        default:
          $ref: "#/components/responses/UnexpectedError"
    put:
      operationId: CreateChecks
      tags:
        - Checks
      summary: Create a new Check
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
      requestBody:
        description: Check to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Check"
      responses:
        204:
          description: Create Check success
        default:
          $ref: "#/components/responses/UnexpectedError"
  /checks/{id}:
    delete:
      operationId: DeleteCheck
      tags:
        - Checks
      summary: Delete Check by id
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: id
          required: true
      responses:
        204:
          description: Delete check by id success
        default:
          $ref: "#/components/responses/UnexpectedError"

  /notification_endpoint:
    get:
      operationId: ListNotificationEndpoint
      tags:
        - Notification Endpoint
      summary: List all notification
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: query
          name: orgID
          required: true
      responses:
        200:
          description: Notification Endpoint List
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationEndpoints"
        default:
          $ref: "#/components/responses/UnexpectedError"
  /notification_endpoint/{id}:
    get:
      operationId: GetNotificationEndpoint
      summary: Get NotificationEndpoint
      tags:
        - Notification Endpoint
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: id
          required: true
      responses:
        200:
          description: NotificationEndpoint Detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationEndpoint"
        default:
          $ref: "#/components/responses/UnexpectedError"

components:
  parameters:
    TraceSpan:
      in: header
      name: Zap-Trace-Span
      schema:
        type: string
      description: OpenTracing span context
      example:
        trace_id: "1"
        span_id: "1"
        baggage:
          key: value
      required: false

  schemas:
    Error:
      properties:
        code:
          description: Code is the machine-readable error code.
          readOnly: true
          type: string
          # This set of enumerations must remain in sync with the constants defined in errors.go
          enum:
            - internal error
            - not found
            - conflict
            - invalid
            - unprocessable entity
            - empty value
            - unavailable
            - forbidden
            - too many requests
            - unauthorized
            - method not allowed
        message:
          readOnly: true
          description: Message is a human-readable message.
          type: string
      required: [ code, message ]

    OnBoardingRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        org:
          type: string


    Organization:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        desc:
          type: string
    Organizations:
      type: array
      items:
        $ref: "#/components/schemas/Organization"

    Otcl:
      type: object
      properties:
        id:
          readOnly: true
          type: string
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        desc:
          type: string
        orgID:
          type: string
          readOnly: true
        type:
          type: string
        content:
          type: string
          description: Config content for the OpenTelemetry Collector
    OtclRequest:
      type: object
      properties:
        name:
          type: string
        desc:
          type: string
        orgID:
          type: string
          readOnly: true
        type:
          type: string
        content:
          type: string
          description: Config content for the OpenTelemetry Collector

    Otcls:
      type: array
      items:
        $ref: "#/components/schemas/Otcl"

    Threshold:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - gt
            - lt
            - eq
            - inside
            - outside
        value:
          type: number
        min:
          type: number
        max:
          type: number

    Condition:
      type: object
      properties:
        status:
          type: string
        pending:
          type: string
        threshold:
          $ref: "#/components/schemas/Threshold"

    Check:
      type: object
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        desc:
          type: string
        status:
          type: string
          enum:
            - active
            - inactive
        orgID:
          type: string
        expr:
          type: string
        conditions:
          type: array
          items:
            $ref: "#/components/schemas/Condition"
    Checks:
      type: array
      items:
        $ref: "#/components/schemas/Check"

    NotificationEndpoint:
      type: object
      required: content_template
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        desc:
          type: string
        status:
          type: string
          enum:
            - active
            - inactive
        url:
          type: string
        method:
          type: string
          enum:
            - POST
            - GET
            - PUT
        headers:
          type: object
        content_template:
          type: string
    NotificationEndpoints:
      type: array
      items:
        $ref: "#/components/schemas/NotificationEndpoint"

  responses:
    UnexpectedError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"